---

- name: stop and disable tinc
  service: >
    name=tinc
    enabled=no
    state=stopped
    pattern=tincd -n {{ netname }}

- name: delete tinc netname directory
  file: >
    path=/etc/tinc/{{ netname }}
    state=absent

#- name: delete nets.boot
#  file: >
#    path=/etc/tinc/nets.boot
#    state=absent

- name: remove {{ netname }} from /etc/tinc/nets.boot file
  lineinfile: >
    dest=/etc/tinc/nets.boot
    line="{{ netname }}"
    mode=0644
    state=absent
  notify:
    - restart tinc
